# config.yml
local_backend: true
# local_backend:
#   # when using a custom proxy server port
#   url: http://localhost:4000/
#   # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
#   allowed_hosts: ['192.168.0.1']

# live
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: '_site/uploads'
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: 'analysis'
    label: 'Analysis'
    folder: '_analysis/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'analysis' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'resources'
    label: 'Resources'
    label_singular: "Resource"
    folder: '_resources/'
    create: true
    # slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Content Type', name: 'content_type', widget: 'hidden', default: 'resource' }
      - { label: 'Type', name: 'type', widget: 'select', allow_add: false, 
        options: [
          "Archives",
          "Electricity",
          "Electric Mobility",
          "Energy Transition",
          "Health",
          "State Clean Energy Goal Tracker",
          "Technology"
          ],
        default: ["Archives"] }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Link', name: 'link', widget: 'string', hint: 'https://example.com' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'text' }
      - { label: 'Publish Date', name: 'posted_on', widget: 'datetime', date_format: "MM.YYYY", time_format: false, format: "LLL" }

  - name: 'sectors'
    label: 'Sectors'
    label_singular: "Sector"
    folder: '_sectors/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Content Type', name: 'content_type', widget: 'hidden', default: 'sector' }
      - { label: 'Breadcrumbs', name: 'breadcrumbs', widget: 'hidden', default: 'sector' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: "Featured Image", name: "feature_image", widget: "image", choose_url: false, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
