# .github/workflows/build.yml
name: ruby-ci-algoliasearch
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          # ruby-version: 2.6 # not needed if `.ruby-version` exists
          # bundler-cache: true # runs `bundle install` and caches installed gems automatically
      - run: wget https://raw.githubusercontent.com/CSIS-iLab/india-states-v2/main/algolia-sync.rb
      - run: chmod +x algolia-sync.rb
      - run: echo 'source "https://rubygems.org"' > Gemfile
      - run: echo 'gem "algoliasearch"' >> Gemfile
      - run: bundle install
      - run: bundle exec ruby algolia-sync.rb
